name: face-recognition
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python
  - ultralytics
  - opencv
  - pytorch
  - pip
  - pip:
      - open-contrib-python
      - torch
      - opencv-python
      - thop
      - torchvision
