name: face-recognition
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - ultralytics
  - opencv
  - pytorch
  - pip
  - pip:
      - tensorflow=2.15
      - opencv-contrib-python
      - torch
      - opencv-python=4.8.0.74
      - thop
      - torchvision
      - albumentations
